name: Build for macOS (M-chip arm64) and Linux

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, macos]
        go-version: ['1.23']

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.os }}
        run: |
          mkdir -p dist
          if [[ "${{ matrix.os }}" == "linux" ]]; then
            GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/ant ./main.go
          elif
            GOOS=darwin GOARCH=arm64 go build -o dist/macos-arm64/ant ./main.go

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/
